# https://docs.atlassian.com/bamboo-specs-docs/6.10.3/specs.html?yaml#yaml-specs-reference
# Branch Base: https://jira.atlassian.com/browse/BAM-19620?_ga=2.142465073.283041144.1571087457-774500003.1487342325
# Permissions: https://community.atlassian.com/t5/Bamboo-questions/Access-denied-creating-deployment-project-through-Bamboo-specs/qaq-p/784854
version: 2
plan:
  project-key: PROJECTKEY
  key: PLANKEY
  name: plan-name
triggers:
- polling: 60
stages:
- Build Stage:
  - Build Stage
branches:
  delete:
    after-inactive-days: never
# ----------------------
Build Stage:
  key: BS
  docker:
    image: docker.io/org/cicdinfra:latest
    use-default-volumes: true
  tasks:
  - script:
      interpreter: /bin/sh
      scripts:
      - /usr/bin/pwsh -c ./scripts/build.ps1
  artifacts:
  - name: environments
    pattern: 'environments/**/*'
  requirements:
  - system.docker.executable
  other:
    clean-working-dir: true
